
rule "$#RULE_NAME#$"
	no-loop true
	lock-on-active true
	agenda-group "$#AGENDA_GROUP#$"
	salience $#SALIENCE#$
	dialect "java"
	when
		$#FROM_TO#$
		$mail : Mail( state == ( MailState.DELIVER ) )
		$headers : Headers( )
		$#CHECK_DOMAINS#$
		$#CHECK_EMAILS#$
		$#CHECK_OWN_DOMAIN#$
	then
		 $mail.getProperties().put("org.mxhero.feature.restricteddelivery","$#RULE_NAME#$");
		 $headers.addHeader("X-mxHero-RestrictedDelivery","rule:$#RULE_NAME#$");
		 $mail.drop("org.mxhero.feature.restricteddelivery");
		 $#REPLAY_COMMAND#$
		 $mail.cmd("org.mxhero.engine.plugin.statistics.command.LogStat",new String[]{"org.mxhero.feature.restricteddelivery.sender",$initialData.getSender().getMail()} );
		 update( $mail );
		 update( $headers );
end
