
rule "$#RULE_NAME#$"
	no-loop true
	lock-on-active true
	agenda-group "$#AGENDA_GROUP#$"
	salience $#SALIENCE#$
	dialect "java"
	when
		$#FROM_TO#$
		$mail : Mail( state == ( MailState.DELIVER ) )
		$headers : Headers( )
		eval(!$mail.getProperties().containsKey("org.mxhero.feature.blocklist:$#AGENDA_GROUP#$"))
		$#CHECK#$
	then
		 $mail.getProperties().put("org.mxhero.feature.blocklist:$#AGENDA_GROUP#$","$#RULE_NAME#$");
		 $headers.addHeader("X-mxHero-BlockList","rule:$#RULE_NAME#$");
		 $mail.drop("org.mxhero.feature.blocklist");
		 $#REPLAY_COMMAND#$
		 $mail.cmd("org.mxhero.engine.plugin.statistics.command.LogStat",new String[]{"org.mxhero.feature.blocklist.sender",$initialData.getSender().getMail()} );
		 Result blockedStat = ($mail.getState().equals(MailState.DROP))?$mail.cmd("org.mxhero.engine.plugin.statistics.command.LogStat",new String[]{"email.blocked","org.mxhero.feature.blocklist"}):null;
		 update( $mail );
		 update( $headers );
end
