SET DB_CLOSE_DELAY 10;        
SET CACHE_SIZE 131072;
SET AUTOCOMMIT TRUE;
;             
CREATE USER IF NOT EXISTS MXHERO SALT 'b9d6b56e4c27cd09' HASH '14f612b5d27cc45f477a03e64ebc7728580ba36d9189ee57a736f015825e7029' ADMIN;       
DROP TABLE IF EXISTS PUBLIC.MAIL_RECORDS CASCADE;             
DROP TABLE IF EXISTS PUBLIC.RECORD_PROPERTIES CASCADE;        
CREATE CACHED TABLE PUBLIC.MAIL_RECORDS(
    INSERT_DATE TIMESTAMP NOT NULL,
    RECORD_SEQUENCE BIGINT NOT NULL,
    CONTENT BLOB NOT NULL,
    ENQUEUED BOOLEAN NOT NULL,
    FLOW VARCHAR(10),
    IN_QUEUE_SINCE BIGINT NOT NULL,
    MESSAGE_ID VARCHAR(1024) NOT NULL,
    MODULE VARCHAR(100) NOT NULL,
    OUTPUT_SERVICE VARCHAR(255),
    PHASE VARCHAR(10) NOT NULL,
    RECIPIENT VARCHAR(255),
    RECIPIENT_DOMAIN_ID VARCHAR(255),
    RECIPIENT_ID VARCHAR(255),
    RECORD_PHASE VARCHAR(10) NOT NULL,
    SENDER VARCHAR(255),
    SENDER_DOMAIN_ID VARCHAR(255),
    SENDER_ID VARCHAR(255),
    STATE VARCHAR(20),
    STATE_REASON VARCHAR(255)
);       
ALTER TABLE PUBLIC.MAIL_RECORDS ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(INSERT_DATE, RECORD_SEQUENCE); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MAIL_RECORDS;            
CREATE INDEX PUBLIC.NEXTINDEX ON PUBLIC.MAIL_RECORDS(ENQUEUED, IN_QUEUE_SINCE, MODULE, PHASE);
CREATE CACHED TABLE PUBLIC.RECORD_PROPERTIES(
    PROPERTY_KEY VARCHAR(80) NOT NULL,
    PROPERTY_VALUE VARCHAR(1024),
    INSERT_DATE TIMESTAMP NOT NULL,
    RECORD_SEQUENCE BIGINT NOT NULL
);             
ALTER TABLE PUBLIC.RECORD_PROPERTIES ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(PROPERTY_KEY, INSERT_DATE, RECORD_SEQUENCE);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RECORD_PROPERTIES;       
ALTER TABLE PUBLIC.RECORD_PROPERTIES ADD CONSTRAINT PUBLIC.FKDA9F49E17D1E3FD FOREIGN KEY(INSERT_DATE, RECORD_SEQUENCE) REFERENCES PUBLIC.MAIL_RECORDS(INSERT_DATE, RECORD_SEQUENCE) NOCHECK;  
