SET DB_CLOSE_DELAY 10;        
SET CACHE_SIZE 32768;
SET AUTOCOMMIT TRUE;
;             
CREATE USER IF NOT EXISTS MXHERO SALT '89fb2a693d5126ad' HASH '085ea784bc0a70aae30a72562af7292b8e39db560b9cbf89026337565cb5fa36' ADMIN;       
     
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.MAIL_RECORDS(
    INSERT_DATE TIMESTAMP NOT NULL,
    RECORD_SEQUENCE BIGINT NOT NULL,
    CONTENT BLOB NOT NULL,
    ENQUEUED BOOLEAN NOT NULL,
    FLOW VARCHAR(10),
    IN_QUEUE_SINCE BIGINT NOT NULL,
    MODULE VARCHAR(100) NOT NULL,
    OUTPUT_SERVICE VARCHAR(255),
    PHASE VARCHAR(10) NOT NULL,
    RECIPIENT VARCHAR(255),
    RECIPIENT_DOMAIN_ID VARCHAR(255),
    RECIPIENT_ID VARCHAR(255),
    RECORD_PHASE VARCHAR(10) NOT NULL,
    SENDER VARCHAR(255),
    SENDER_DOMAIN_ID VARCHAR(255),
    SENDER_ID VARCHAR(255),
    STATE VARCHAR(20),
    STATE_REASON VARCHAR(255)
);
ALTER TABLE PUBLIC.MAIL_RECORDS ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_C PRIMARY KEY(INSERT_DATE, RECORD_SEQUENCE); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MAIL_RECORDS;            
CREATE INDEX IF NOT EXISTS PUBLIC.NEXTINDEX ON PUBLIC.MAIL_RECORDS(ENQUEUED, IN_QUEUE_SINCE, MODULE, PHASE);
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.RECORD_PROPERTIES(
    PROPERTY_KEY VARCHAR(80) NOT NULL,
    PROPERTY_VALUE VARCHAR(1024),
    INSERT_DATE TIMESTAMP NOT NULL,
    RECORD_SEQUENCE BIGINT NOT NULL
);             
ALTER TABLE PUBLIC.RECORD_PROPERTIES ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_7 PRIMARY KEY(PROPERTY_KEY, INSERT_DATE, RECORD_SEQUENCE);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RECORD_PROPERTIES;       
ALTER TABLE PUBLIC.RECORD_PROPERTIES ADD CONSTRAINT IF NOT EXISTS PUBLIC.FKDA9F49E17D1E3FD FOREIGN KEY(INSERT_DATE, RECORD_SEQUENCE) REFERENCES PUBLIC.MAIL_RECORDS(INSERT_DATE, RECORD_SEQUENCE) NOCHECK ON DELETE CASCADE;  

