#!/usr/bin/perl

use strict;
use warnings;
no warnings qw(uninitialized);

use File::Basename;
use lib dirname($0) . '/installer-lib';
use Term::UI;
use Term::ReadLine;

use mxHero::Config;
use mxHero::Locale;
use mxHero::App;
use mxHero::ClamAV;
use mxHero::JDK;
use mxHero::MySQL;
use mxHero::Postfix;
use mxHero::SpamAssassin;
use mxHero::Tomcat;
use mxHero::Tools;


print T('*************************************'),"\n";
print T('WELCOME TO THE MXHERO LINUX INSTALLER'),"\n";
print T('*************************************'),"\n\n";

## Do basic checks here
# Must be linux
if ( $^O !~ /linux/i ) {
	print T("This installer only supports Linux Operating Systems")."\n";
	exit 1;
}
# Must be root
if ( $> ) {
	print T("This script requires root privledges").".\n\n";
	exit 1;
}


my $error;

if ( ! &mxHero::Tools::mxHeroCheck() )
{
	if ( #  if one fails (exit 0) then condition fails immediately
			&mxHero::App::download ( \$error ) &&
			&mxHero::JDK::download ( \$error ) &&
			&mxHero::MySQL::install ( \$error ) &&
			&mxHero::Tomcat::install ( \$error ) &&
			&mxHero::Postfix::install ( \$error ) &&
			&mxHero::ClamAV::install ( \$error ) &&
			&mxHero::SpamAssassin::install ( \$error ) &&
			&mxHero::JDK::install ( \$error ) &&
			&mxHero::App::install ( \$error ) ) &&
			&mxHero::Config::install ( \$error )
		{
			print T('INSTALLED'),"\n"; # Success message
		} else {
			print T("INSTALL FAILED. ERROR:\n$error"),"\n"; # Fail message
		}
}
else # upgrade
{
	if (
			&mxHero::App::download ();
			# no JDK download
			&mxHero::MySQL::upgrade ( \$error ) &&
			&mxHero::Tomcat::upgrade ( \$error ) &&
			&mxHero::Postfix::upgrade ( \$error ) &&
			&mxHero::ClamAV::upgrade ( \$error ) &&
			&mxHero::SpamAssassin::upgrade ( \$error ) &&
			&mxHero::JDK::upgrade ( \$error ) &&
			&mxHero::App::upgrade ( \$error ) ) &&
			&mxHero::Config::upgrade ( \$error )
		{
			print T('UPGRADED'),"\n"; # Success message
	
		} else {
			print T("UPGRADE FAILED. ERROR:\n$error"),"\n"; # Fail message
		}
}

exit (0);
