#!/usr/bin/perl

use IO::Handle; STDOUT->autoflush(1);

use strict;
use warnings;
no warnings qw(uninitialized);

use File::Copy;
use File::Basename;
use lib dirname($0) . '/installer-lib';
use Term::UI;
use Term::ReadLine;

use mxHero::Config;
use mxHero::Locale;
use mxHero::App;
use mxHero::ClamAV;
use mxHero::JDK;
use mxHero::MySQL;
use mxHero::Postfix;
use mxHero::SpamAssassin;
use mxHero::Tomcat;
use mxHero::Tools;
use mxHero::HeroAttach;


print T('*************************************'),"\n";
print T('WELCOME TO THE MXHERO LINUX INSTALLER'),"\n";
print T('*************************************'),"\n";

## Do basic checks here
# Must be linux
if ( $^O !~ /linux/i ) {
	print T("This installer only supports Linux Operating Systems")."\n";
	exit 1;
}
# Check distribution & versions
my $distri  = &mxHero::Tools::getDistri();
my $version = &mxHero::Tools::getDistriVersion();
if ( $distri eq 'Ubuntu' ) {
	$version =~ m/^(\d+)\..+/;
	my $major = $1;
	if ( $major < 10 ) {
		print "Linux $distri $version not supported or tested. Cancelling install.\n\n";
		exit;
	}
} 
elsif ( $distri eq 'Redhat' ) {
	&mxHero::Tools::adjustRedhat();
}
# Must be root
if ( $> ) {
	print T("This script requires root privledges").".\n\n";
	exit 1;
}
# Should have updated packages
&mxHero::Tools::packageListUpdate();
# Need to be on UTC
if ( ! &mxHero::Tools::isUTC() ) {
	&mxHero::Tools::setUTC();
}

my $error;

if ( ! &mxHero::Tools::mxHeroVersion() )
{
	if ( #  if one fails (exit 0) then condition fails immediately
			&mxHero::MySQL::install ( \$error ) &&
			&mxHero::Tomcat::install ( \$error ) &&
			&mxHero::Postfix::install ( \$error ) &&
			&mxHero::ClamAV::install ( \$error ) &&
			&mxHero::SpamAssassin::install ( \$error ) &&
			&mxHero::App::install ( \$error ) &&
			&mxHero::JDK::install ( \$error ) &&
			&mxHero::MySQL::createDatabase ( \$error ) &&
			&mxHero::HeroAttach::install ( \$error )
			)
		{
			if ( ! copy( "$myConfig{INSTALLER_PATH}/VERSION" , $myConfig{MXHERO_PATH} ) ) {
				warn $!;
				print "\n\n!! MXHERO INSTALL FAILED !!\n\n";
				exit 1;
			}
			# here forward when install run, will be 'upgrade'.
			print T("\n!! MXHERO INSTALLED !!"),"\n"; # Success message
			#&_startMxHero();
			# Consider a reload dialogue to reload all mxHero services for immediate usage
			
			# Zimbra note
			if ( &mxHero::Tools::zimbraCheck() ) {
				print "\n*** NOTE FOR ZIMBRA INSTALLATIONS ***\n";
				print "mxHero is providing SpamAssassin and ClamAV.\n";
				print "You can disable Zimbra's SpamAssassin and ClamAV by running the command:\n";
				print "\t# su - zimbra\n";
				print "\t\$ zmprov ms `zmhostname` -zimbraServiceEnabled antivirus -zimbraServiceEnabled antispam\n\n";

				my $term = Term::ReadLine->new( 'mxHero' );
				my $bool = $term->ask_yn( prompt => T("Disable Zimbra antivirus and antispam? "),
							   default  => 'y',
							   print_me => T("The installer can submit this command now?") );
				if ( $bool ) {
					system( "su - zimbra -c 'zmprov ms `zmhostname` -zimbraServiceEnabled antivirus -zimbraServiceEnabled antispam'" );
				}
			}

			print "\n\n** Admin Panel **\n";
			print "Once mxHero is started, you can access the mxHero admin panel at:\n";
			print "\thttp://your_ip:8080/mxhero.\n\n";
			print "The default admin login credentials are:\n";
			print "\tLogin: admin\n";
			print "\tPass:  password (REMEMBER TO CHANGE!)\n\n";
			print "\n** Important Notes **\n";
			print "You probably need to restart/reload:\n";
			print "  Tomcat;\n";
			print "  Postfix/Zimbra;\n";
			print "  ClamAV;\n";
			print "  Spamassassin;\n";
			print "  mxHero;\n";
			print "Or just reboot your machine for all systems to start up.\n\n";

			print "Visit http://www.mxhero.com for support and updates.\n\n";
		} else {
			print T("INSTALL FAILED. ERROR:\n$error"),"\n"; # Fail message
		}
}
else # upgrade
{
	if (
			&mxHero::MySQL::upgrade ( \$error ) &&
			&mxHero::Tomcat::upgrade ( \$error ) &&
			&mxHero::Postfix::upgrade ( \$error ) &&
			&mxHero::ClamAV::upgrade ( \$error ) &&
			&mxHero::SpamAssassin::upgrade ( \$error ) &&
			&mxHero::App::upgrade ( \$error ) &&
			&mxHero::JDK::upgrade ( \$error ) &&
			&mxHero::HeroAttach::upgrade ( \$error )
			)
		{
			if ( ! copy( "$myConfig{INSTALLER_PATH}/VERSION" , $myConfig{MXHERO_PATH} ) ) {
				warn $!;
				print "\n\n!! MXHERO INSTALL FAILED !!\n\n";
				exit 1;
			}
			print T("\n!! MXHERO UPGRADED !!"),"\n"; # Success message
			print T("Remember to restart services.")."\n\n";
	
		} else {
			print T("UPGRADE FAILED. ERROR:\n$error"),"\n"; # Fail message
		}
}


sub _startMxHero
{
	print "mxHero will now be started.\n";
	print "Hit <enter> to start...\n";
	while ( <STDIN> ) { # wait for enter
		last;
	}
	
	my $distri = &mxHero::Tools::getDistri();
	
	if ( $distri eq "Ubuntu" || $distri eq "Debian" ) {
		system("/etc/init.d/mxhero start");
###		warn "TEST: doing /etc/init.d/mxhero start\n"; ### TESTING
	} elsif ( $distri eq "Redhat" ) {
		# TODO
	} elsif ( $distri eq "Suse" ) {
		# TODO
	} else {
		# could not identify Distribution
		warn "Unknown Linux Distribution.";
		return 0;
	}
}

exit (0);
